version: 2
jobs:
  build:
    working_directory: ~/estimeo-highlights-sample/
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "hello world"
      - run: bash .circleci/setup-heroku.sh
      - run: sudo npm install -g npm@latest
      - run: npm install
      - run: npm run build
      - run: npm run test
      - deploy:
          name: Deploy Master to Heroku
          command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ]; then
                      git push heroku master
                      heroku run npm build
                      heroku run nmp start
                      heroku restart
                  fi
